### ISSUE TITLE
Minor issues after upgrading Statamic 4.x

### ISSUE THREAD

**Issue by imbwaldo** [statamic/starter-kit-podcaster#14]
I've upgraded my Podcaster site, in a local dev environment, to Statamic 4.18.0, got Laravel up to v10.x, and PHP to v8.2.x. The styling of the CP in this upgraded/updated local site is a bit off—the old/live site's control panel is obviously receiving some styles that are no longer present in my local version.

A bit of exploration revealed that the old site is using cp.sass—a file that's definitely absent from my updated local site. Is there an upgrade path for this starter kit that I need to follow? Is there some aspect of Forma that I'm overlooking?

**Comment by jackmcdade** [comment]
I'm a bit confused. — I'm not quite sure how your old/live site's control panel would be receiving files from your local version. Which version is upgraded – live or local? Which version has the wrong styling? Have you run `php please statamic:install` to make sure you have the latest CP assets?

**Comment by imbwaldo** [comment]
Sorry. I sow confusion wherever I go.

I've updated a local copy of the site. The original site's still live and has not been updated. When I inspect styles in the CP of the live site, I see this …

<img width="456" alt="Screenshot 2023-08-23 at 12 54 52 PM" src="https://github.com/statamic/starter-kit-podcaster/assets/1582379/46996f31-576a-41bb-a16c-578d1fb2c929">

The path is `webpack:///resources/sass/cp.sass`

I ran `php please statamic:install` in my project but got an error: `There are no commands defined in the "statamic" namespace.`

I apologize for being so utterly useless here …

**Comment by imbwaldo** [comment]
Here's what the old CP looks like:

![Screenshot 2023-08-23 at 1 03 43 PM](https://github.com/statamic/starter-kit-podcaster/assets/1582379/1c35af93-78a8-41f3-9fe9-e17d69e3daea)


And here's what the CP looks like on my local, updated site:

![Screenshot 2023-08-23 at 1 03 26 PM](https://github.com/statamic/starter-kit-podcaster/assets/1582379/481db0c2-6f9e-477c-af8a-a23b10217942)

It's not a huge deal, but padding styles are definitely missing.

**Comment by jackmcdade** [comment]
Oh that's because we just haven't updated the Podcaster widget for v4. I was waiting for this to get merged and just hadn't gotten to it yet. https://github.com/statamic/cms/pull/8305

**Comment by imbwaldo** [comment]
Aha! I'm sure you've got plenty of things on your plate.

So it's just a matter of running an update, once one is available?

**Comment by imbwaldo** [comment]
That was one of my unasked questions. I assumed, in situations like this, where there's a major Statamic update with breaking changes, that some sort of work would need to be done on the starter kit, but I wasn't sure if/how that'd happen. If you intend to post copy-and-paste code (and instructions) to this repo, that'd be awesome.

Thanks very much!

**Comment by jackmcdade** [comment]
Yeah so we probably should have made the Widget an Addon so it could be updated later. Didn't think that far ahead :)

**Comment by jackmcdade** [comment]
Drop the contents of this Gist in your `resources/views/widgets/getting-started.blade.php` file and you should be good to go: https://gist.github.com/jackmcdade/63a85c3a8f7e612683347badd2cd286a

**Comment by imbwaldo** [comment]
Thanks very much! I'll pop that in.
