### ISSUE TITLE
Can't use the latest version of Alpine because the Turbo bridge breaks

### ISSUE THREAD

**Issue by ellimondo** [statamic/starter-kit-podcaster#6]
Hi

Me again – back like a bad smell all the way across the Atlantic!

I ran `npm production` on the server (and I've tried this locally too) and mix breaks the site.js output which borks the player so it stops working – I guess coz the code is already minified. I've commented js out of the webpack file for now as I don't really need it. Just thought I would log it 'ere.

Kind regards

Jon

```
Uncaught RangeError: Maximum call stack size exceeded
    at t (site.js?id=1a2694795b8318a7f846:25)
    at site.js?id=1a2694795b8318a7f846:25
    at Array.forEach (<anonymous>)
    at t (site.js?id=1a2694795b8318a7f846:25)
    at site.js?id=1a2694795b8318a7f846:25
    at Array.forEach (<anonymous>)
    at t (site.js?id=1a2694795b8318a7f846:25)
    at site.js?id=1a2694795b8318a7f846:25
    at Array.forEach (<anonymous>)
    at t (site.js?id=1a2694795b8318a7f846:25)
```

**Comment by jackmcdade** [comment]
Hmm, I can't recreate this one. Did you make any changes to the npm packages (e.g. `package.json`)?

**Comment by ellimondo** [comment]
I haven’t changed anything from the initial installation. Let me run it again locally when I get in tomorrow.

**Comment by ellimondo** [comment]
Hi

I've tested this again locally today using `npm run production` and even when I run `npm run dev` it breaks the pre-compiled javascript that comes with the package. I am using Mix v6.0.39 fwiw.

The error is at line 4938 of the non-minified script:

`let isObject = (val) => typeof val === "object" && !Array.isArray(val) && val !== null;`

There's also a missing file which is only referenced as a commented out line in the generated js file:

`[Error] Failed to load resource: the server responded with a status of 404 () (plyr.min.js.map, line 0)`

**Comment by josephrlee** [comment]
I'm getting the same error as well, it looks like it's preventing the player from working.

**Comment by jackmcdade** [comment]
Looking into it this morning! I'm sorry I missed the notification before 😅

**Comment by jackmcdade** [comment]
Okay I found a temporary fix but sticking with an older version of Alpine. It seems both Turbo and Alpine made some breaking changes (even though neither marked anything as breaking) that broke the bridge script between both. 

I'll see if I can work out a permanent fix, but in the mean time if you use `"alpinejs": "~3.0.6",` as your `package.json` dependency everything should work!

**Comment by ellimondo** [comment]
Thanks Jack. That works again now.

**Comment by josephrlee** [comment]
Thanks Jack!

**Comment by jackmcdade** [comment]
Resolved by dropping Turbo in favor of Livewire 3.
