### ISSUE TITLE
Cannot Install due to owen-oj/laravel-getid3 dependency

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/starter-kit-podcaster#8]
I used 
statamic new mysite statamic/starter-kit-podcaster

Everything was successful until the following.

> @php artisan key:generate --ansi
Application key set successfully.
Validating starter kit license...
Starter kit license valid!
Collections cleared successfully.
Navigations cleared successfully.
Trees cleared successfully.
Taxonomies cleared successfully.
Assets cleared successfully.
Globals cleared successfully.
Forms cleared successfully.
Users cleared successfully.
User groups cleared successfully.
User roles cleared successfully.
Blueprints cleared successfully.
Fieldsets cleared successfully.
Views cleared successfully.
Statamic configs reset successfully.
Preparing starter kit [statamic/starter-kit-podcaster]...
Cleaning up temporary files...
./composer.json has been updated
Running composer update owen-oj/laravel-getid3 --with-dependencies
Loading composer repositories with package information
Dependency laravel/framework is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires owen-oj/laravel-getid3 ^1.3 -> satisfiable by owen-oj/laravel-getid3[v1.3].
    - owen-oj/laravel-getid3 v1.3 requires illuminate/support ^5.0|^6.0|^7.0|^8.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Cannot install due to error with [owen-oj/laravel-getid3] dependency.

In NewCommand.php line 476:

  There was a problem installing Statamic with the chosen starter kit!

new [--dev] [--license [LICENSE]] [--local] [--with-config] [--without-dependencies] [--v2] [-f|--force] [--] <name> [<starter-kit>]

**Comment by jasonvarga** [comment]
Looks like that package was updated to support Laravel 9 recently https://github.com/Owen-oj/laravel-getid3/releases/tag/v2.0

We'll need to update our dependency to handle the 2.0 release.

https://github.com/statamic/starter-kit-podcaster/blob/8ee384a9ef25fce072e65bdf15833d30593804f5/starter-kit.yaml#L24

Thanks for pointing this out.

**Comment by jackmcdade** [comment]
I think we can remove the dependency actually, we now can read `duration` in core. Let me rework the logic here.

**Comment by jasonvarga** [comment]
True, even better.

**Comment by jackmcdade** [comment]
Fixed!
